// Continents and countries data

export const continentsData = {
  "North America": {
    icon: "/images/north-america.png",
    color: "blue",
    countries: [
      "United States",
      "Canada",
      "Mexico",
      "Guatemala",
      "Belize",
      "El Salvador",
      "Honduras",
      "Nicaragua",
      "Costa Rica",
      "Panama",
      "Cuba",
      "Jamaica",
      "Haiti",
      "Dominican Republic",
      "Bahamas",
      "Barbados",
      "Trinidad and Tobago",
      "Antigua and Barbuda",
      "Saint Lucia",
      "Grenada",
      "Saint Vincent and the Grenadines",
      "Dominica",
      "Saint Kitts and Nevis",
    ],
  },
  Europe: {
    icon: "/images/europe.png",
    color: "green",
    countries: [
      "United Kingdom",
      "Germany",
      "France",
      "Italy",
      "Spain",
      "Netherlands",
      "Belgium",
      "Switzerland",
      "Austria",
      "Sweden",
      "Norway",
      "Denmark",
      "Finland",
      "Poland",
      "Czech Republic",
      "Hungary",
      "Portugal",
      "Greece",
      "Ireland",
      "Croatia",
      "Slovenia",
      "Slovakia",
      "Estonia",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Cyprus",
      "Iceland",
      "Romania",
      "Bulgaria",
      "Serbia",
      "Montenegro",
      "Bosnia and Herzegovina",
      "North Macedonia",
      "Albania",
      "Moldova",
      "Ukraine",
      "Belarus",
    ],
  },
  Asia: {
    icon: "/images/asia.png",
    color: "red",
    countries: [
      "China",
      "India",
      "Japan",
      "South Korea",
      "Singapore",
      "Malaysia",
      "Thailand",
      "Indonesia",
      "Philippines",
      "Vietnam",
      "Taiwan",
      "Hong Kong",
      "Macau",
      "Bangladesh",
      "Pakistan",
      "Sri Lanka",
      "Nepal",
      "Bhutan",
      "Maldives",
      "Myanmar",
      "Cambodia",
      "Laos",
      "Brunei",
      "Mongolia",
      "Kazakhstan",
      "Uzbekistan",
      "Kyrgyzstan",
      "Tajikistan",
      "Turkmenistan",
      "Afghanistan",
      "Iran",
      "Iraq",
      "Turkey",
      "Syria",
      "Lebanon",
      "Jordan",
      "Israel",
      "Palestine",
      "Saudi Arabia",
      "United Arab Emirates",
      "Qatar",
      "Kuwait",
      "Bahrain",
      "Oman",
      "Yemen",
    ],
  },
  Africa: {
    icon: "/images/africa.png",
    color: "orange",
    countries: [
      "South Africa",
      "Nigeria",
      "Egypt",
      "Kenya",
      "Morocco",
      "Ghana",
      "Ethiopia",
      "Uganda",
      "Tanzania",
      "Algeria",
      "Tunisia",
      "Libya",
      "Sudan",
      "Zimbabwe",
      "Zambia",
      "Botswana",
      "Namibia",
      "Mozambique",
      "Madagascar",
      "Mauritius",
      "Seychelles",
      "Rwanda",
      "Burundi",
      "Democratic Republic of Congo",
      "Republic of Congo",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Niger",
      "Mali",
      "Burkina Faso",
      "Ivory Coast",
      "Liberia",
      "Sierra Leone",
      "Guinea",
      "Guinea-Bissau",
      "Senegal",
      "Gambia",
      "Cape Verde",
      "Mauritania",
      "Benin",
      "Togo",
      "Gabon",
      "Equatorial Guinea",
      "São Tomé and Príncipe",
      "Angola",
      "Malawi",
      "Lesotho",
      "Eswatini",
      "Comoros",
      "Djibouti",
      "Eritrea",
      "Somalia",
    ],
  },
  "South America": {
    icon: "/images/south-america.png",
    color: "purple",
    countries: [
      "Brazil",
      "Argentina",
      "Chile",
      "Colombia",
      "Peru",
      "Venezuela",
      "Ecuador",
      "Bolivia",
      "Paraguay",
      "Uruguay",
      "Guyana",
      "Suriname",
      "French Guiana",
    ],
  },
  Oceania: {
    icon: "/images/oceania.png",
    color: "teal",
    countries: [
      "Australia",
      "New Zealand",
      "Papua New Guinea",
      "Fiji",
      "Solomon Islands",
      "Vanuatu",
      "Samoa",
      "Tonga",
      "Kiribati",
      "Palau",
      "Marshall Islands",
      "Micronesia",
      "Nauru",
      "Tuvalu",
      "Cook Islands",
      "Niue",
    ],
  },
}

// Helper functions
export function getContinentsList() {
  return Object.keys(continentsData)
}

export function getCountriesByContinent(continent) {
  return continentsData[continent]?.countries || []
}

export function getContinentInfo(continent) {
  return continentsData[continent] || null
}

export function getAllCountries() {
  return Object.values(continentsData).flatMap((continent) => continent.countries)
}

export function getContinentByCountry(country) {
  for (const [continentName, continentData] of Object.entries(continentsData)) {
    if (continentData.countries.includes(country)) {
      return continentName
    }
  }
  return null
}

export function getTopCountriesByContinent(continent, count = 8) {
  const countries = getCountriesByContinent(continent)
  return countries.slice(0, count)
}

// Popular countries for quick access
export const popularCountriesByContinent = {
  "North America": ["United States", "Canada", "Mexico","Guatemala","Haiti","Dominican Republic"],
  Europe: ["United Kingdom", "Germany", "France", "Italy", "Spain", "Netherlands"],
  Asia: ["China", "India", "Japan", "South Korea", "Singapore", "Malaysia"],
  Africa: ["South Africa", "Nigeria", "Egypt", "Kenya", "Morocco", "Ghana"],
  "South America": ["Brazil", "Argentina", "Chile", "Colombia","Uruguay","Ecuador"],
  Oceania: ["Australia", "New Zealand","Papua New Guinea","Hawaii (US)","Fiji","Solomon Islands"],
}