// Location data for countries, states, and cities

export const locationData = {
  "United States": {
    states: {
      California: [
        "Los Angeles",
        "San Francisco",
        "San Diego",
        "Sacramento",
        "San Jose",
        "Fresno",
        "Oakland",
        "Santa Ana",
        "Anaheim",
        "Riverside",
      ],
      "New York": [
        "New York City",
        "Buffalo",
        "Rochester",
        "Yonkers",
        "Syracuse",
        "Albany",
        "New Rochelle",
        "Mount Vernon",
        "Schenectady",
        "Utica",
      ],
      Texas: [
        "Houston",
        "San Antonio",
        "Dallas",
        "Austin",
        "Fort Worth",
        "El Paso",
        "Arlington",
        "Corpus Christi",
        "Plano",
        "Laredo",
      ],
      Florida: [
        "Jacksonville",
        "Miami",
        "Tampa",
        "Orlando",
        "St. Petersburg",
        "Hialeah",
        "Tallahassee",
        "Fort Lauderdale",
        "Port St. Lucie",
        "Cape Coral",
      ],
      Illinois: [
        "Chicago",
        "Aurora",
        "Rockford",
        "Joliet",
        "Naperville",
        "Springfield",
        "Peoria",
        "Elgin",
        "Waukegan",
        "Cicero",
      ],
      Pennsylvania: [
        "Philadelphia",
        "Pittsburgh",
        "Allentown",
        "Erie",
        "Reading",
        "Scranton",
        "Bethlehem",
        "Lancaster",
        "Harrisburg",
        "Altoona",
      ],
      Ohio: [
        "Columbus",
        "Cleveland",
        "Cincinnati",
        "Toledo",
        "Akron",
        "Dayton",
        "Parma",
        "Canton",
        "Youngstown",
        "Lorain",
      ],
      Georgia: [
        "Atlanta",
        "Augusta",
        "Columbus",
        "Savannah",
        "Athens",
        "Sandy Springs",
        "Roswell",
        "Macon",
        "Johns Creek",
        "Albany",
      ],
      "North Carolina": [
        "Charlotte",
        "Raleigh",
        "Greensboro",
        "Durham",
        "Winston-Salem",
        "Fayetteville",
        "Cary",
        "Wilmington",
        "High Point",
        "Asheville",
      ],
      Michigan: [
        "Detroit",
        "Grand Rapids",
        "Warren",
        "Sterling Heights",
        "Lansing",
        "Ann Arbor",
        "Flint",
        "Dearborn",
        "Livonia",
        "Westland",
      ],
    },
  },
  "United Kingdom": {
    states: {
      England: [
        "London",
        "Birmingham",
        "Manchester",
        "Leeds",
        "Liverpool",
        "Sheffield",
        "Bristol",
        "Newcastle",
        "Nottingham",
        "Leicester",
      ],
      Scotland: [
        "Glasgow",
        "Edinburgh",
        "Aberdeen",
        "Dundee",
        "Stirling",
        "Perth",
        "Inverness",
        "Paisley",
        "East Kilbride",
        "Hamilton",
      ],
      Wales: [
        "Cardiff",
        "Swansea",
        "Newport",
        "Wrexham",
        "Barry",
        "Caerphilly",
        "Bridgend",
        "Neath",
        "Port Talbot",
        "Cwmbran",
      ],
      "Northern Ireland": [
        "Belfast",
        "Derry",
        "Lisburn",
        "Newtownabbey",
        "Bangor",
        "Craigavon",
        "Castlereagh",
        "Ballymena",
        "Newtownards",
        "Carrickfergus",
      ],
    },
  },
  Canada: {
    states: {
      Ontario: [
        "Toronto",
        "Ottawa",
        "Hamilton",
        "London",
        "Kitchener",
        "Windsor",
        "Oshawa",
        "Barrie",
        "Guelph",
        "Kingston",
      ],
      Quebec: [
        "Montreal",
        "Quebec City",
        "Laval",
        "Gatineau",
        "Longueuil",
        "Sherbrooke",
        "Saguenay",
        "Trois-Rivières",
        "Terrebonne",
        "Saint-Jean-sur-Richelieu",
      ],
      "British Columbia": [
        "Vancouver",
        "Victoria",
        "Surrey",
        "Burnaby",
        "Richmond",
        "Abbotsford",
        "Coquitlam",
        "Kelowna",
        "Saanich",
        "Delta",
      ],
      Alberta: [
        "Calgary",
        "Edmonton",
        "Red Deer",
        "Lethbridge",
        "St. Albert",
        "Medicine Hat",
        "Grande Prairie",
        "Airdrie",
        "Spruce Grove",
        "Leduc",
      ],
      Manitoba: [
        "Winnipeg",
        "Brandon",
        "Steinbach",
        "Thompson",
        "Portage la Prairie",
        "Winkler",
        "Selkirk",
        "Morden",
        "Dauphin",
        "The Pas",
      ],
      Saskatchewan: [
        "Saskatoon",
        "Regina",
        "Prince Albert",
        "Moose Jaw",
        "Swift Current",
        "Yorkton",
        "North Battleford",
        "Estevan",
        "Weyburn",
        "Lloydminster",
      ],
    },
  },
  Australia: {
    states: {
      "New South Wales": [
        "Sydney",
        "Newcastle",
        "Wollongong",
        "Maitland",
        "Albury",
        "Wagga Wagga",
        "Port Macquarie",
        "Tamworth",
        "Orange",
        "Dubbo",
      ],
      Victoria: [
        "Melbourne",
        "Geelong",
        "Ballarat",
        "Bendigo",
        "Frankston",
        "Mildura",
        "Shepparton",
        "Warrnambool",
        "Wodonga",
        "Traralgon",
      ],
      Queensland: [
        "Brisbane",
        "Gold Coast",
        "Townsville",
        "Cairns",
        "Toowoomba",
        "Rockhampton",
        "Mackay",
        "Bundaberg",
        "Hervey Bay",
        "Gladstone",
      ],
      "Western Australia": [
        "Perth",
        "Fremantle",
        "Rockingham",
        "Mandurah",
        "Bunbury",
        "Kalgoorlie",
        "Geraldton",
        "Albany",
        "Busselton",
        "Ellenbrook",
      ],
      "South Australia": [
        "Adelaide",
        "Mount Gambier",
        "Whyalla",
        "Murray Bridge",
        "Port Lincoln",
        "Port Pirie",
        "Victor Harbor",
        "Gawler",
        "Port Augusta",
        "Kadina",
      ],
      Tasmania: [
        "Hobart",
        "Launceston",
        "Devonport",
        "Burnie",
        "Somerset",
        "Wynyard",
        "Kingston",
        "Ulverstone",
        "Glenorchy",
        "Brighton",
      ],
    },
  },
  Germany: {
    states: {
      Bavaria: [
        "Munich",
        "Nuremberg",
        "Augsburg",
        "Würzburg",
        "Regensburg",
        "Ingolstadt",
        "Fürth",
        "Erlangen",
        "Bayreuth",
        "Bamberg",
      ],
      "North Rhine-Westphalia": [
        "Cologne",
        "Düsseldorf",
        "Dortmund",
        "Essen",
        "Duisburg",
        "Bochum",
        "Wuppertal",
        "Bielefeld",
        "Bonn",
        "Münster",
      ],
      "Baden-Württemberg": [
        "Stuttgart",
        "Mannheim",
        "Karlsruhe",
        "Freiburg",
        "Heidelberg",
        "Ulm",
        "Heilbronn",
        "Pforzheim",
        "Reutlingen",
        "Esslingen",
      ],
      Berlin: ["Berlin"],
      Hamburg: ["Hamburg"],
      Hesse: [
        "Frankfurt",
        "Wiesbaden",
        "Kassel",
        "Darmstadt",
        "Offenbach",
        "Hanau",
        "Marburg",
        "Fulda",
        "Rüsselsheim",
        "Gießen",
      ],
    },
  },
  France: {
    states: {
      "Île-de-France": [
        "Paris",
        "Boulogne-Billancourt",
        "Saint-Denis",
        "Argenteuil",
        "Montreuil",
        "Créteil",
        "Nanterre",
        "Colombes",
        "Aulnay-sous-Bois",
        "Rueil-Malmaison",
      ],
      "Provence-Alpes-Côte d'Azur": [
        "Marseille",
        "Nice",
        "Toulon",
        "Aix-en-Provence",
        "Avignon",
        "Antibes",
        "Cannes",
        "La Seyne-sur-Mer",
        "Hyères",
        "Arles",
      ],
      "Auvergne-Rhône-Alpes": [
        "Lyon",
        "Saint-Étienne",
        "Grenoble",
        "Villeurbanne",
        "Clermont-Ferrand",
        "Valence",
        "Chambéry",
        "Annecy",
        "Bourg-en-Bresse",
        "Roanne",
      ],
      "Nouvelle-Aquitaine": [
        "Bordeaux",
        "Limoges",
        "Poitiers",
        "Pau",
        "La Rochelle",
        "Mérignac",
        "Pessac",
        "Bayonne",
        "Angoulême",
        "Niort",
      ],
      Occitanie: [
        "Toulouse",
        "Montpellier",
        "Nîmes",
        "Perpignan",
        "Béziers",
        "Narbonne",
        "Carcassonne",
        "Albi",
        "Tarbes",
        "Castres",
      ],
      "Hauts-de-France": [
        "Lille",
        "Amiens",
        "Tourcoing",
        "Roubaix",
        "Dunkerque",
        "Calais",
        "Villeneuve-d'Ascq",
        "Saint-Quentin",
        "Beauvais",
        "Compiègne",
      ],
    },
  },
  India: {
    states: {
      Maharashtra: [
        "Mumbai",
        "Pune",
        "Nagpur",
        "Thane",
        "Nashik",
        "Aurangabad",
        "Solapur",
        "Amravati",
        "Kolhapur",
        "Sangli",
      ],
      Karnataka: [
        "Bangalore",
        "Mysore",
        "Hubli",
        "Mangalore",
        "Belgaum",
        "Gulbarga",
        "Davanagere",
        "Bellary",
        "Bijapur",
        "Shimoga",
      ],
      "Tamil Nadu": [
        "Chennai",
        "Coimbatore",
        "Madurai",
        "Tiruchirappalli",
        "Salem",
        "Tirunelveli",
        "Erode",
        "Vellore",
        "Thoothukudi",
        "Dindigul",
      ],
      "Uttar Pradesh": [
        "Lucknow",
        "Kanpur",
        "Ghaziabad",
        "Agra",
        "Varanasi",
        "Meerut",
        "Allahabad",
        "Bareilly",
        "Aligarh",
        "Moradabad",
      ],
      "West Bengal": [
        "Kolkata",
        "Howrah",
        "Durgapur",
        "Asansol",
        "Siliguri",
        "Malda",
        "Bardhaman",
        "Baharampur",
        "Habra",
        "Kharagpur",
      ],
      Gujarat: [
        "Ahmedabad",
        "Surat",
        "Vadodara",
        "Rajkot",
        "Bhavnagar",
        "Jamnagar",
        "Junagadh",
        "Gandhinagar",
        "Anand",
        "Navsari",
      ],
      Rajasthan: [
        "Jaipur",
        "Jodhpur",
        "Kota",
        "Bikaner",
        "Ajmer",
        "Udaipur",
        "Bhilwara",
        "Alwar",
        "Bharatpur",
        "Sikar",
      ],
      Telangana: [
        "Hyderabad",
        "Warangal",
        "Nizamabad",
        "Khammam",
        "Karimnagar",
        "Ramagundam",
        "Mahbubnagar",
        "Nalgonda",
        "Adilabad",
        "Suryapet",
      ],
      Kerala: [
        "Thiruvananthapuram",
        "Kochi",
        "Kozhikode",
        "Thrissur",
        "Kollam",
        "Palakkad",
        "Alappuzha",
        "Malappuram",
        "Kannur",
        "Kasaragod",
      ],
      Punjab: [
        "Ludhiana",
        "Amritsar",
        "Jalandhar",
        "Patiala",
        "Bathinda",
        "Mohali",
        "Firozpur",
        "Batala",
        "Pathankot",
        "Moga",
      ],
    },
  },
  Japan: {
    states: {
      Tokyo: [
        "Tokyo",
        "Shibuya",
        "Shinjuku",
        "Harajuku",
        "Ginza",
        "Akihabara",
        "Roppongi",
        "Asakusa",
        "Ikebukuro",
        "Ueno",
      ],
      Osaka: [
        "Osaka",
        "Sakai",
        "Higashiosaka",
        "Hirakata",
        "Toyonaka",
        "Suita",
        "Takatsuki",
        "Yao",
        "Neyagawa",
        "Kishiwada",
      ],
      Kanagawa: [
        "Yokohama",
        "Kawasaki",
        "Sagamihara",
        "Fujisawa",
        "Chigasaki",
        "Hiratsuka",
        "Odawara",
        "Yamato",
        "Zushi",
        "Kamakura",
      ],
      Aichi: [
        "Nagoya",
        "Toyota",
        "Okazaki",
        "Ichinomiya",
        "Kasugai",
        "Anjo",
        "Toyohashi",
        "Nishio",
        "Kariya",
        "Komaki",
      ],
      Hokkaido: [
        "Sapporo",
        "Asahikawa",
        "Hakodate",
        "Kushiro",
        "Tomakomai",
        "Obihiro",
        "Otaru",
        "Ebetsu",
        "Kitami",
        "Iwamizawa",
      ],
      Kyoto: ["Kyoto", "Uji", "Kameoka", "Joyo", "Muko", "Nagaokakyo", "Yawata", "Kyotanabe", "Fukuchiyama", "Maizuru"],
    },
  },
}

// Helper functions
export function getCountriesWithStates() {
  return Object.keys(locationData)
}

export function getStatesByCountry(country) {
  return locationData[country] ? Object.keys(locationData[country].states) : []
}

export function getCitiesByCountryAndState(country, state) {
  return locationData[country]?.states[state] || []
}

export function getAllCitiesByCountry(country) {
  if (!locationData[country]) return []

  const allCities = []
  Object.values(locationData[country].states).forEach((cities) => {
    allCities.push(...cities)
  })
  return allCities
}

// Search functions
export function searchCitiesInCountry(country, searchTerm) {
  const allCities = getAllCitiesByCountry(country)
  return allCities.filter((city) => city.toLowerCase().includes(searchTerm.toLowerCase()))
}

export function searchStatesInCountry(country, searchTerm) {
  const states = getStatesByCountry(country)
  return states.filter((state) => state.toLowerCase().includes(searchTerm.toLowerCase()))
}
