// Topics data organized by categories

export const topicsData = {
  "Engineering and Technology": [
    "Aeronautical",
    "AI",
    "Architecture",
    "Artificial Intelligence",
    "Aviation Technology",
    "Big Data",
    "Biotechnology",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Science",
    "Cybersecurity",
    "Data Science",
    "Electrical Engineering",
    "Electronics",
    "Environmental Engineering",
    "Industrial Engineering",
    "Information Technology",
    "IoT",
    "Machine Learning",
    "Materials Science",
    "Mechanical Engineering",
    "Nanotechnology",
    "Network Security",
    "Robotics",
    "Software Engineering",
    "Telecommunications",
  ],
  "Medical And Health Science": [
    "Allergy",
    "Alternative Health",
    "Anesthesia",
    "Asthma",
    "Autism",
    "Ayurveda",
    "Cardiology",
    "Clinical Research",
    "Dentistry",
    "Dermatology",
    "Emergency Medicine",
    "Endocrinology",
    "Epidemiology",
    "Gastroenterology",
    "Genetics",
    "Geriatrics",
    "Gynecology",
    "Health Informatics",
    "Immunology",
    "Internal Medicine",
    "Mental Health",
    "Neurology",
    "Nursing",
    "Nutrition",
    "Oncology",
    "Ophthalmology",
    "Orthopedics",
    "Pediatrics",
    "Pharmacy",
    "Physical Therapy",
    "Psychiatry",
    "Public Health",
    "Radiology",
    "Surgery",
  ],
  "Business and Economics": [
    "Accounting",
    "Banking",
    "Business",
    "Business Ethics",
    "Business Statistics",
    "E-commerce",
    "Economics",
    "Entrepreneurship",
    "Finance",
    "Financial Planning",
    "Human Resources",
    "International Business",
    "Investment",
    "Leadership",
    "Management",
    "Marketing",
    "Operations Management",
    "Organizational Behavior",
    "Project Management",
    "Quality Management",
    "Real Estate",
    "Risk Management",
    "Strategic Planning",
    "Supply Chain",
    "Taxation",
  ],
  Education: [
    "Adult Education",
    "Childhood Education",
    "Curriculum Development",
    "Distance Learning",
    "Educational Leadership",
    "Educational Psychology",
    "Educational Technology",
    "Higher Education",
    "Language Learning",
    "Learning Disabilities",
    "Online Education",
    "Pedagogy",
    "Primary Education",
    "Secondary Education",
    "Special Education",
    "STEM Education",
    "Teacher Training",
    "Vocational Education",
  ],
  "Social Sciences and Humanities": [
    "Anthropology",
    "Archaeology",
    "Art History",
    "Communication",
    "Cultural Studies",
    "Geography",
    "History",
    "International Relations",
    "Journalism",
    "Language Studies",
    "Literature",
    "Media Studies",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Religion",
    "Social Work",
    "Sociology",
    "Translation Studies",
  ],
  "Sports Science": [
    "Athletic Training",
    "Biomechanics",
    "Exercise Physiology",
    "Fitness",
    "Kinesiology",
    "Nutrition",
    "Physical Education",
    "Recreation",
    "Rehabilitation",
    "Sports Management",
    "Sports Medicine",
    "Sports Psychology",
  ],
  "Physical and life sciences": [
    "Astronomy",
    "Biology",
    "Botany",
    "Chemistry",
    "Earth Sciences",
    "Ecology",
    "Environmental Science",
    "Geology",
    "Marine Biology",
    "Meteorology",
    "Microbiology",
    "Oceanography",
    "Physics",
    "Zoology",
  ],
  Agriculture: [
    "Agricultural Economics",
    "Agricultural Engineering",
    "Agronomy",
    "Animal Science",
    "Crop Science",
    "Food Science",
    "Forestry",
    "Horticulture",
    "Plant Pathology",
    "Soil Science",
    "Sustainable Agriculture",
    "Veterinary Science",
  ],
  "Mathematics and statistics": [
    "Applied Mathematics",
    "Biostatistics",
    "Computational Mathematics",
    "Data Analytics",
    "Mathematical Modeling",
    "Pure Mathematics",
    "Statistical Analysis",
    "Statistics",
  ],
  Law: [
    "Business Law",
    "Constitutional Law",
    "Criminal Law",
    "Environmental Law",
    "Family Law",
    "Human Rights",
    "Intellectual Property",
    "International Law",
    "Labor Law",
    "Legal Ethics",
  ],
  Interdisciplinary: [
    "Cognitive Science",
    "Digital Humanities",
    "Environmental Studies",
    "Gender Studies",
    "Global Studies",
    "Information Science",
    "Peace Studies",
    "Science Communication",
    "Sustainability",
    "Urban Studies",
  ],
}

// Helper functions
export function getCategoriesList() {
  return Object.keys(topicsData)
}

export function getTopicsByCategory(category) {
  return topicsData[category] || []
}

export function getAllTopics() {
  return Object.values(topicsData).flat()
}

export function searchTopics(searchTerm) {
  const allTopics = getAllTopics()
  return allTopics.filter((topic) => topic.toLowerCase().includes(searchTerm.toLowerCase()))
}

export function getCategoryByTopic(topic) {
  for (const [category, topics] of Object.entries(topicsData)) {
    if (topics.includes(topic)) {
      return category
    }
  }
  return null
}
